// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy2zRGkmlw-zjftd1lSAtiHPgfNLTE4_k',
    appId: '1:145622451662:android:1cae4c0757eb5e609e179f',
    messagingSenderId: '145622451662',
    projectId: 'chatpix-ai-5091f',
    storageBucket: 'chatpix-ai-5091f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1QvKTXulfDy7TVwpLXBqoZQDkWOfPGZs',
    appId: '1:145622451662:ios:4bd9c195880ca1bb9e179f',
    messagingSenderId: '145622451662',
    projectId: 'chatpix-ai-5091f',
    storageBucket: 'chatpix-ai-5091f.appspot.com',
    androidClientId: '145622451662-d8gacc2olge4ano2ca0bh9if6lg0tfab.apps.googleusercontent.com',
    iosClientId: '145622451662-shlvlel749516bhgh3e1kq59r53ukg5u.apps.googleusercontent.com',
    iosBundleId: 'com.chatpix.ai',
  );
}
